{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "VGG with MNIST data.ipynb",
      "provenance": [],
      "authorship_tag": "ABX9TyNUL4DHIt7vxhFYdVF9rF4W",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sushgho/Msc-Project/blob/sushgho-patch-1/VGG_with_MNIST_data.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "K4Udk3aUn5QS"
      },
      "source": [
        "from __future__ import absolute_import\n",
        "from __future__ import division\n",
        "from __future__ import print_function\n",
        "\n",
        "# Imports\n",
        "import numpy as np\n",
        "import tensorflow as tf\n",
        "import matplotlib.pyplot as plt\n",
        "#tf.logging.set_verbosity(tf.logging.INFO)\n",
        "\n",
        "%matplotlib inline\n",
        "np.random.seed(1)"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "7sYFlJxt4Hr7",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 358
        },
        "outputId": "1262bc68-eb35-4362-9bc3-839e99668036"
      },
      "source": [
        "pip install tensorflow==1.14\n"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: tensorflow==1.14 in /usr/local/lib/python3.6/dist-packages (1.14.0)\n",
            "Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (3.10.0)\n",
            "Requirement already satisfied: tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.14.0)\n",
            "Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (0.9.0)\n",
            "Requirement already satisfied: numpy<2.0,>=1.14.5 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.18.4)\n",
            "Requirement already satisfied: keras-applications>=1.0.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.0.8)\n",
            "Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.28.1)\n",
            "Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (0.34.2)\n",
            "Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.12.0)\n",
            "Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.12.1)\n",
            "Requirement already satisfied: tensorboard<1.15.0,>=1.14.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.14.0)\n",
            "Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (0.8.1)\n",
            "Requirement already satisfied: gast>=0.2.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (0.3.3)\n",
            "Requirement already satisfied: google-pasta>=0.1.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (0.2.0)\n",
            "Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.1.0)\n",
            "Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow==1.14) (1.1.0)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf>=3.6.1->tensorflow==1.14) (46.1.3)\n",
            "Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from keras-applications>=1.0.6->tensorflow==1.14) (2.10.0)\n",
            "Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14) (3.2.1)\n",
            "Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/dist-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14) (1.0.1)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "lTfRuCPetxWq",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 358
        },
        "outputId": "a65f3248-4014-4450-c9ca-71277dc72c1e"
      },
      "source": [
        "pip install tensorflow-gpu==1.14"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: tensorflow-gpu==1.14 in /usr/local/lib/python3.6/dist-packages (1.14.0)\n",
            "Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (1.1.0)\n",
            "Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (3.10.0)\n",
            "Requirement already satisfied: tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (1.14.0)\n",
            "Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (1.28.1)\n",
            "Requirement already satisfied: keras-applications>=1.0.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (1.0.8)\n",
            "Requirement already satisfied: numpy<2.0,>=1.14.5 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (1.18.4)\n",
            "Requirement already satisfied: google-pasta>=0.1.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (0.2.0)\n",
            "Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (1.12.1)\n",
            "Requirement already satisfied: gast>=0.2.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (0.3.3)\n",
            "Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (0.34.2)\n",
            "Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (1.1.0)\n",
            "Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (0.9.0)\n",
            "Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (0.8.1)\n",
            "Requirement already satisfied: tensorboard<1.15.0,>=1.14.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (1.14.0)\n",
            "Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==1.14) (1.12.0)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf>=3.6.1->tensorflow-gpu==1.14) (46.1.3)\n",
            "Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from keras-applications>=1.0.6->tensorflow-gpu==1.14) (2.10.0)\n",
            "Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/dist-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow-gpu==1.14) (1.0.1)\n",
            "Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow-gpu==1.14) (3.2.1)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "XyhrPbRGs2Hm",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 85
        },
        "outputId": "38171d17-31ad-4e0a-a299-3faf3872f693"
      },
      "source": [
        "# Loading the data (MNIST)\n",
        "mnist = tf.contrib.learn.datasets.load_dataset(\"mnist\")\n",
        "train_data = mnist.train.images  # Returns np.array\n",
        "train_labels = np.asarray(mnist.train.labels, dtype=np.int32)\n",
        "eval_data = mnist.test.images  # Returns np.array\n",
        "eval_labels = np.asarray(mnist.test.labels, dtype=np.int32)"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Extracting MNIST-data/train-images-idx3-ubyte.gz\n",
            "Extracting MNIST-data/train-labels-idx1-ubyte.gz\n",
            "Extracting MNIST-data/t10k-images-idx3-ubyte.gz\n",
            "Extracting MNIST-data/t10k-labels-idx1-ubyte.gz\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "71JI5oUZs2ES",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 281
        },
        "outputId": "040d2f77-5296-4616-aa57-3b6f7d1377cc"
      },
      "source": [
        "\n",
        "index = 7\n",
        "plt.imshow(train_data[index].reshape(28, 28))\n",
        "print (\"y = \" + str(np.squeeze(train_labels[index])))"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "y = 0\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAPsAAAD4CAYAAAAq5pAIAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+j8jraAAAOpklEQVR4nO3df5BV9XnH8c8jrIAIKQRLt+APgjiRtAlkVjSRNGZsCZI/MJMOIzUGW2fWWmhkEqcl9g9N/+gwHX9PnaQkkhAn6jjxF5nYGGRMGKMhLA6VH2JAgiMEliqmEqj8fPrHHpwV93zvcu8599zd5/2a2bl3z3PPPQ8HPpx7z/ee+zV3F4DB74yqGwDQHIQdCIKwA0EQdiAIwg4EMbSZGzvThvlwjWzmJoFQ3tVBHfHD1letobCb2WxJ90oaIum77r409fjhGqlL7cpGNgkgYa2vzq3V/TLezIZIul/SVZKmSppvZlPrfT4A5WrkPfsMSdvdfYe7H5H0iKS5xbQFoGiNhH2CpDd6/b4rW/Y+ZtZpZl1m1nVUhxvYHIBGlH423t2XuXuHu3e0aVjZmwOQo5Gw75Z0bq/fJ2bLALSgRsK+TtIUM5tkZmdKukbSymLaAlC0uofe3P2YmS2S9Ix6ht6Wu/vmwjoDUKiGxtnd/WlJTxfUC4AS8XFZIAjCDgRB2IEgCDsQBGEHgiDsQBCEHQiCsANBEHYgCMIOBEHYgSAIOxAEYQeCIOxAEIQdCIKwA0EQdiAIwg4EQdiBIAg7EARhB4Jo6pTNaEGXfTxZ/u3Nfc7++57ffHZFsn7hz6/PrU3+mw3JdVEsjuxAEIQdCIKwA0EQdiAIwg4EQdiBIAg7EATj7IPc3sWfTtb/bdHyZH3WiIPJ+lFPb//eGY/k1u7TR9Mr19D9j+k/258+tDW3dvyt/Q1teyBqKOxmtlPSAUnHJR1z944imgJQvCKO7J9z9zcLeB4AJeI9OxBEo2F3ST8zs/Vm1tnXA8ys08y6zKzrqA43uDkA9Wr0ZfxMd99tZn8saZWZbXX3Nb0f4O7LJC2TpNE2tsbpHABlaejI7u67s9t9kp6QNKOIpgAUr+6wm9lIMxt18r6kWZI2FdUYgGI18jJ+vKQnzOzk8zzk7j8tpCu8jw0blqy/Pe+TubU1t9yZXPcsO7Ounpph1zfS4+jrFt6TrD+6cGJu7b57vpRc95xvv5isD0R1h93dd0j6RIG9ACgRQ29AEIQdCIKwA0EQdiAIwg4EwSWuA8CO2/OH1iRp81f+I1Etd2jt27//SLL+nw9+Ibc2QS8k1z384RPJepsNSdavHbUnt3bJkruS616nryXrA3FojiM7EARhB4Ig7EAQhB0IgrADQRB2IAjCDgTBOHsLqHUJ68ipbzepkw/6r0OjkvXH/mlWsj7hJ+mx9Kpc1Jb+/MEj37gjWf/89MXp579x3Wn3VDaO7EAQhB0IgrADQRB2IAjCDgRB2IEgCDsQBOPsTWBD07v5tX9NX6++pSN1vXpjOt+4Ilnf96X0OPuw3eWNJ1/wkyPJ+sfPvz5ZX/+pB3Jrta6FnzR0eLI+emtbst6KOLIDQRB2IAjCDgRB2IEgCDsQBGEHgiDsQBCMszfB4b+cnqxv+XJ54+g3/+7yZL37C+nx4uNv/a7Idk7LkOdeStbPey69/hOvtufW5p29r56WBrSaR3YzW25m+8xsU69lY81slZlty27HlNsmgEb152X89yXNPmXZEkmr3X2KpNXZ7wBaWM2wu/saSftPWTxX0ors/gpJVxfcF4CC1fuefby7n5xIa6+k8XkPNLNOSZ2SNFxn1bk5AI1q+Gy8u7skT9SXuXuHu3e0Kf3FigDKU2/Yu82sXZKy23inNoEBpt6wr5S0ILu/QNJTxbQDoCw137Ob2cOSrpA0zsx2SbpN0lJJj5rZDZJelzSvzCZbXfdXP52s/8NNT5a6/dRY+m8/m/7//MShU8+9YrCqGXZ3n59TurLgXgCUiI/LAkEQdiAIwg4EQdiBIAg7EASXuPbTGZ+4OLe29Kv5X1ksSVeOONTQtmt93XPqMtXBPLRm0z+WrF/Qlr5ENmX70cPJ+od2HKv7uavCkR0IgrADQRB2IAjCDgRB2IEgCDsQBGEHgmCcvZ8+82D+mG2j4+i1rHvyz5P1CW+9UOr2W9WrN6W/5mzGsNwvUKrpmYNTk/URT/267ueuCkd2IAjCDgRB2IEgCDsQBGEHgiDsQBCEHQiCcfbMmzd+Klm/acydiWp6pps9x/8vWf/a6+mp8s57vDtZP56sDlxDJ52frP9i9t01nmFE3dt+fv+FNR7xZt3PXRWO7EAQhB0IgrADQRB2IAjCDgRB2IEgCDsQBOPsmQPpIV2dfUZ6LD3ljn2fS2/7M7XGbAfemG4RXl3Ynqy3D6l/HP3tE+8m63vvnZysjxyAfyc1j+xmttzM9pnZpl7Lbjez3Wa2IfuZU26bABrVn5fx35c0u4/ld7v7tOzn6WLbAlC0mmF39zWSBu8cQkAQjZygW2RmL2cv88fkPcjMOs2sy8y6jio9fxaA8tQb9m9JmixpmqQ9knKvEnH3Ze7e4e4dbTUuGAFQnrrC7u7d7n7c3U9I+o6kGcW2BaBodYXdzHqPiXxR0qa8xwJoDTXH2c3sYUlXSBpnZrsk3SbpCjObJskl7ZR0Y4k9Dng/fbYjWZ+kF5vUSYsxS5Z9SHmbvmXXVcn6yB+tLW/jFakZdnef38fiB0roBUCJ+LgsEARhB4Ig7EAQhB0IgrADQXCJaxO0/3KwftlzY/732kuT9a3z7i9t2y/8Mj0l82T9qrRtV4UjOxAEYQeCIOxAEIQdCIKwA0EQdiAIwg4EwTh7E5x/69ZkvfvHTWqkBEMnTkjWty08L7e29supabClWlNh1/LwgfG5tYu+93Zy3cH4yQiO7EAQhB0IgrADQRB2IAjCDgRB2IEgCDsQBOPsTTDzj7Yn609OuSxZP75tR5HtvM+Qi6ck69sWjEvW7/nr7yXrs0YcTFTLnSFoxcK5ubWhm9eXuu1WxJEdCIKwA0EQdiAIwg4EQdiBIAg7EARhB4JgnD0z5bt7kvVvzpmWW7vtnA3Jdf929BvJ+pCVJ5L1jYcmJuuNmDbyF8n6taPS+6VMKw+OSdZvefaaZP2jv9qcW0vv8cGp5pHdzM41s+fMbIuZbTazm7PlY81slZlty27TfzMAKtWfl/HHJH3d3adKukzSQjObKmmJpNXuPkXS6ux3AC2qZtjdfY+7v5TdPyDpFUkTJM2VtCJ72ApJV5fVJIDGndZ7djO7QNJ0SWsljXf3k2/o9krq8wu/zKxTUqckDddZ9fYJoEH9PhtvZmdLekzSYnd/p3fN3V2S97Weuy9z9w5372gr+cIHAPn6FXYza1NP0H/o7o9ni7vNrD2rt0vaV06LAIpQ82W8mZmkByS94u539SqtlLRA0tLs9qlSOmySYzt2JuvP3Dczt7b4m+npfT90xvBk/SujdyfrqlVvYYf8SG7t/v35w5mStObvLknWL+r6dbIecXgtpT/v2S+XdJ2kjWZ2ckD5VvWE/FEzu0HS65LmldMigCLUDLu7Py/JcspXFtsOgLLwcVkgCMIOBEHYgSAIOxAEYQeCsJ4PvzXHaBvrl9rgO4E/eV16HP3vz/l5sn5xW1uB3TTX/b+fnKw/eO9VubVxy14sup3w1vpqveP7+xw948gOBEHYgSAIOxAEYQeCIOxAEIQdCIKwA0HwVdIFeO2Sd5P1JRfOT69//Z8k65+f3ZWs39mefz39x36wKLmuHU+Wa5r80FvJ+rgtjKW3Co7sQBCEHQiCsANBEHYgCMIOBEHYgSAIOxAE17MDgwjXswMg7EAUhB0IgrADQRB2IAjCDgRB2IEgaobdzM41s+fMbIuZbTazm7Plt5vZbjPbkP3MKb9dAPXqz5dXHJP0dXd/ycxGSVpvZquy2t3ufkd57QEoSn/mZ98jaU92/4CZvSJpQtmNASjWab1nN7MLJE2XtDZbtMjMXjaz5WY2JmedTjPrMrOuozrcULMA6tfvsJvZ2ZIek7TY3d+R9C1JkyVNU8+R/86+1nP3Ze7e4e4dbRpWQMsA6tGvsJtZm3qC/kN3f1yS3L3b3Y+7+wlJ35E0o7w2ATSqP2fjTdIDkl5x97t6LW/v9bAvStpUfHsAitKfs/GXS7pO0kYz25Atu1XSfDObJskl7ZR0YykdAihEf87GPy+pr+tjny6+HQBl4RN0QBCEHQiCsANBEHYgCMIOBEHYgSAIOxAEYQeCIOxAEIQdCIKwA0EQdiAIwg4EQdiBIJo6ZbOZ/Y+k13stGifpzaY1cHpatbdW7Uuit3oV2dv57n5OX4Wmhv0DGzfrcveOyhpIaNXeWrUvid7q1azeeBkPBEHYgSCqDvuyiref0qq9tWpfEr3Vqym9VfqeHUDzVH1kB9AkhB0IopKwm9lsM3vVzLab2ZIqeshjZjvNbGM2DXVXxb0sN7N9Zrap17KxZrbKzLZlt33OsVdRby0xjXdimvFK913V0583/T27mQ2R9BtJfyVpl6R1kua7+5amNpLDzHZK6nD3yj+AYWZ/IekPkn7g7n+WLft3SfvdfWn2H+UYd//nFuntdkl/qHoa72y2ovbe04xLulrS9apw3yX6mqcm7LcqjuwzJG139x3ufkTSI5LmVtBHy3P3NZL2n7J4rqQV2f0V6vnH0nQ5vbUEd9/j7i9l9w9IOjnNeKX7LtFXU1QR9gmS3uj1+y611nzvLulnZrbezDqrbqYP4919T3Z/r6TxVTbTh5rTeDfTKdOMt8y+q2f680Zxgu6DZrr7JyVdJWlh9nK1JXnPe7BWGjvt1zTezdLHNOPvqXLf1Tv9eaOqCPtuSef2+n1itqwluPvu7HafpCfUelNRd5+cQTe73VdxP+9ppWm8+5pmXC2w76qc/ryKsK+TNMXMJpnZmZKukbSygj4+wMxGZidOZGYjJc1S601FvVLSguz+AklPVdjL+7TKNN5504yr4n1X+fTn7t70H0lz1HNG/jVJ/1JFDzl9fUTSf2c/m6vuTdLD6nlZd1Q95zZukPRhSaslbZP0rKSxLdTbg5I2SnpZPcFqr6i3mep5if6ypA3Zz5yq912ir6bsNz4uCwTBCTogCMIOBEHYgSAIOxAEYQeCIOxAEIQdCOL/Af7YPko053cVAAAAAElFTkSuQmCC\n",
            "text/plain": [
              "<Figure size 432x288 with 1 Axes>"
            ]
          },
          "metadata": {
            "tags": [],
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "-0VHktyQs2A1",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 119
        },
        "outputId": "5ddf3a94-fe1a-46ce-a1e7-4447d82b1a53"
      },
      "source": [
        "\n",
        "print (\"number of training examples = \" + str(train_data.shape[0]))\n",
        "print (\"number of evaluation examples = \" + str(eval_data.shape[0]))\n",
        "print (\"X_train shape: \" + str(train_data.shape))\n",
        "print (\"Y_train shape: \" + str(train_labels.shape))\n",
        "print (\"X_test shape: \" + str(eval_data.shape))\n",
        "print (\"Y_test shape: \" + str(eval_labels.shape))"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "number of training examples = 55000\n",
            "number of evaluation examples = 10000\n",
            "X_train shape: (55000, 784)\n",
            "Y_train shape: (55000,)\n",
            "X_test shape: (10000, 784)\n",
            "Y_test shape: (10000,)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "iJymmB5Ls18-"
      },
      "source": [
        "def cnn_model_fn(features, labels, mode):\n",
        "    # Input Layer\n",
        "    input_height, input_width = 28, 28\n",
        "    input_channels = 1\n",
        "    input_layer = tf.reshape(features[\"x\"], [-1, input_height, input_width, input_channels])\n",
        "\n",
        "    # Convolutional Layer #1 and Pooling Layer #1\n",
        "    conv1_1 = tf.layers.conv2d(inputs=input_layer, filters=64, kernel_size=[3, 3], padding=\"same\", activation=tf.nn.relu)\n",
        "    conv1_2 = tf.layers.conv2d(inputs=conv1_1, filters=64, kernel_size=[3, 3], padding=\"same\", activation=tf.nn.relu)\n",
        "    pool1 = tf.layers.max_pooling2d(inputs=conv1_2, pool_size=[2, 2], strides=2, padding=\"same\")\n",
        "    \n",
        "    # Convolutional Layer #2 and Pooling Layer #2\n",
        "    conv2_1 = tf.layers.conv2d(inputs=pool1, filters=128, kernel_size=[3, 3], padding=\"same\", activation=tf.nn.relu)\n",
        "    conv2_2 = tf.layers.conv2d(inputs=conv2_1, filters=128, kernel_size=[3, 3], padding=\"same\", activation=tf.nn.relu)\n",
        "    pool2 = tf.layers.max_pooling2d(inputs=conv2_2, pool_size=[2, 2], strides=2, padding=\"same\")\n",
        "\n",
        "    # Convolutional Layer #3 and Pooling Layer #3\n",
        "    conv3_1 = tf.layers.conv2d(inputs=pool2, filters=256, kernel_size=[3, 3], padding=\"same\", activation=tf.nn.relu)\n",
        "    conv3_2 = tf.layers.conv2d(inputs=conv3_1, filters=256, kernel_size=[3, 3], padding=\"same\", activation=tf.nn.relu)\n",
        "    pool3 = tf.layers.max_pooling2d(inputs=conv3_2, pool_size=[2, 2], strides=2, padding=\"same\")\n",
        "\n",
        "    # Convolutional Layer #4 and Pooling Layer #4\n",
        "    conv4_1 = tf.layers.conv2d(inputs=pool3, filters=512, kernel_size=[3, 3], padding=\"same\", activation=tf.nn.relu)\n",
        "    conv4_2 = tf.layers.conv2d(inputs=conv4_1, filters=512, kernel_size=[3, 3], padding=\"same\", activation=tf.nn.relu)\n",
        "    pool4 = tf.layers.max_pooling2d(inputs=conv4_2, pool_size=[2, 2], strides=2, padding=\"same\")\n",
        "\n",
        "    # Convolutional Layer #5 and Pooling Layer #5\n",
        "    conv5_1 = tf.layers.conv2d(inputs=pool4, filters=512, kernel_size=[3, 3], padding=\"same\", activation=tf.nn.relu)\n",
        "    conv5_2 = tf.layers.conv2d(inputs=conv5_1, filters=512, kernel_size=[3, 3], padding=\"same\", activation=tf.nn.relu)\n",
        "    pool5 = tf.layers.max_pooling2d(inputs=conv5_2, pool_size=[2, 2], strides=2, padding=\"same\")\n",
        "\n",
        "    # FC Layers\n",
        "    pool5_flat = tf.contrib.layers.flatten(pool5)\n",
        "    FC1 = tf.layers.dense(inputs=pool5_flat, units=4096, activation=tf.nn.relu)\n",
        "    FC2 = tf.layers.dense(inputs=FC1, units=4096, activation=tf.nn.relu)\n",
        "    FC3 = tf.layers.dense(inputs=FC2, units=1000, activation=tf.nn.relu)\n",
        "\n",
        "    \"\"\"the training argument takes a boolean specifying whether or not the model is currently \n",
        "    being run in training mode; dropout will only be performed if training is true. here, \n",
        "    we check if the mode passed to our model function cnn_model_fn is train mode. \"\"\"\n",
        "    dropout = tf.layers.dropout(inputs=FC3, rate=0.4, training=mode == tf.estimator.ModeKeys.TRAIN)\n",
        "    \n",
        "    # Logits Layer or the output layer. which will return the raw values for our predictions.\n",
        "    # Like FC layer, logits layer is another dense layer. We leave the activation function empty \n",
        "    # so we can apply the softmax\n",
        "    logits = tf.layers.dense(inputs=dropout, units=10)\n",
        "    \n",
        "    # Then we make predictions based on raw output\n",
        "    predictions = {\n",
        "        # Generate predictions (for PREDICT and EVAL mode)\n",
        "        # the predicted class for each example - a vlaue from 0-9\n",
        "        \"classes\": tf.argmax(input=logits, axis=1),\n",
        "        # to calculate the probablities for each target class we use the softmax\n",
        "        \"probabilities\": tf.nn.softmax(logits, name=\"softmax_tensor\")\n",
        "    }\n",
        "    \n",
        "    # so now our predictions are compiled in a dict object in python and using that we return an estimator object\n",
        "    if mode == tf.estimator.ModeKeys.PREDICT:\n",
        "        return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions)\n",
        "    \n",
        "    \n",
        "    '''Calculate Loss (for both TRAIN and EVAL modes): computes the softmax entropy loss. \n",
        "    This function both computes the softmax activation function as well as the resulting loss.'''\n",
        "    loss = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits)\n",
        "\n",
        "    # Configure the Training Options (for TRAIN mode)\n",
        "    if mode == tf.estimator.ModeKeys.TRAIN:\n",
        "        optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)\n",
        "        train_op = optimizer.minimize(loss=loss, global_step=tf.train.get_global_step())\n",
        "        \n",
        "        return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)\n",
        "\n",
        "    # Add evaluation metrics (for EVAL mode)\n",
        "    eval_metric_ops = {\n",
        "        \"accuracy\": tf.metrics.accuracy(labels=labels,\n",
        "                                        predictions=predictions[\"classes\"])}\n",
        "    return tf.estimator.EstimatorSpec(mode=mode,\n",
        "                                      loss=loss,\n",
        "                                      eval_metric_ops=eval_metric_ops)"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "lBX6Vv9Ws13Z",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "outputId": "470208f5-0d5f-4c88-d1d9-aa08c31a8be2"
      },
      "source": [
        "# Create the Estimator\n",
        "mnist_classifier = tf.estimator.Estimator(model_fn=cnn_model_fn,\n",
        "                                          model_dir=\"/tmp/mnist_vgg13_model\")\n",
        "\n",
        "# Train the model\n",
        "train_input_fn = tf.estimator.inputs.numpy_input_fn(x={\"x\": train_data},\n",
        "                                                    y=train_labels,\n",
        "                                                    batch_size=100,\n",
        "                                                    num_epochs=100,\n",
        "                                                    shuffle=True)\n",
        "mnist_classifier.train(input_fn=train_input_fn,\n",
        "                       steps=None,\n",
        "                       hooks=None)\n",
        "\n",
        "# Evaluate the model and print results\n",
        "eval_input_fn = tf.estimator.inputs.numpy_input_fn(x={\"x\": eval_data},\n",
        "                                                   y=eval_labels,\n",
        "                                                   num_epochs=1,\n",
        "                                                   shuffle=False)\n",
        "eval_results = mnist_classifier.evaluate(input_fn=eval_input_fn)\n",
        "print(eval_results)"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "INFO:tensorflow:Using default config.\n",
            "INFO:tensorflow:Using config: {'_model_dir': '/tmp/mnist_vgg13_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true\n",
            "graph_options {\n",
            "  rewrite_options {\n",
            "    meta_optimizer_iterations: ONE\n",
            "  }\n",
            "}\n",
            ", '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f6564c75f98>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6567b9ea20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6567b9ea20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6567b9ea20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6567b9ea20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6567b9ea20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f6569ffcfd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f6569ffcfd0>>: AttributeError: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f6569ffcfd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f6569ffcfd0>>: AttributeError: module 'gast' has no attribute 'Num'\n",
            "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f65bdfb7898>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Create CheckpointSaverHook.\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/mnist_vgg13_model/model.ckpt-11000\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Saving checkpoints for 11000 into /tmp/mnist_vgg13_model/model.ckpt.\n",
            "INFO:tensorflow:loss = 2.2950437, step = 11000\n",
            "INFO:tensorflow:global_step/sec: 11.5517\n",
            "INFO:tensorflow:loss = 2.303797, step = 11100 (8.660 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6848\n",
            "INFO:tensorflow:loss = 2.3013265, step = 11200 (8.557 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8743\n",
            "INFO:tensorflow:loss = 2.304727, step = 11300 (8.424 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.71\n",
            "INFO:tensorflow:loss = 2.2919998, step = 11400 (8.538 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8993\n",
            "INFO:tensorflow:loss = 2.2902515, step = 11500 (8.404 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7152\n",
            "INFO:tensorflow:loss = 2.30297, step = 11600 (8.534 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8724\n",
            "INFO:tensorflow:loss = 2.299555, step = 11700 (8.423 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7398\n",
            "INFO:tensorflow:loss = 2.29812, step = 11800 (8.518 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9319\n",
            "INFO:tensorflow:loss = 2.289136, step = 11900 (8.383 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7745\n",
            "INFO:tensorflow:loss = 2.2982001, step = 12000 (8.494 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9412\n",
            "INFO:tensorflow:loss = 2.3001602, step = 12100 (8.373 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7634\n",
            "INFO:tensorflow:loss = 2.3053145, step = 12200 (8.500 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9351\n",
            "INFO:tensorflow:loss = 2.2956612, step = 12300 (8.383 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7634\n",
            "INFO:tensorflow:loss = 2.2981768, step = 12400 (8.497 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9217\n",
            "INFO:tensorflow:loss = 2.2932136, step = 12500 (8.386 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7656\n",
            "INFO:tensorflow:loss = 2.296587, step = 12600 (8.501 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9256\n",
            "INFO:tensorflow:loss = 2.2952127, step = 12700 (8.384 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7694\n",
            "INFO:tensorflow:loss = 2.2920845, step = 12800 (8.499 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9113\n",
            "INFO:tensorflow:loss = 2.2906122, step = 12900 (8.394 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7782\n",
            "INFO:tensorflow:loss = 2.2918556, step = 13000 (8.491 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8908\n",
            "INFO:tensorflow:loss = 2.296401, step = 13100 (8.409 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7546\n",
            "INFO:tensorflow:loss = 2.29101, step = 13200 (8.509 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9362\n",
            "INFO:tensorflow:loss = 2.303659, step = 13300 (8.377 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7207\n",
            "INFO:tensorflow:loss = 2.2938113, step = 13400 (8.532 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9268\n",
            "INFO:tensorflow:loss = 2.2984474, step = 13500 (8.382 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7689\n",
            "INFO:tensorflow:loss = 2.2959583, step = 13600 (8.499 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9144\n",
            "INFO:tensorflow:loss = 2.2992427, step = 13700 (8.391 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7118\n",
            "INFO:tensorflow:loss = 2.3038304, step = 13800 (8.538 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8908\n",
            "INFO:tensorflow:loss = 2.3027947, step = 13900 (8.412 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7419\n",
            "INFO:tensorflow:loss = 2.2951443, step = 14000 (8.515 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9251\n",
            "INFO:tensorflow:loss = 2.297183, step = 14100 (8.388 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7086\n",
            "INFO:tensorflow:loss = 2.2989745, step = 14200 (8.542 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8797\n",
            "INFO:tensorflow:loss = 2.2966754, step = 14300 (8.416 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7011\n",
            "INFO:tensorflow:loss = 2.290982, step = 14400 (8.544 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8835\n",
            "INFO:tensorflow:loss = 2.2966297, step = 14500 (8.416 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7066\n",
            "INFO:tensorflow:loss = 2.2973275, step = 14600 (8.545 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9438\n",
            "INFO:tensorflow:loss = 2.3012822, step = 14700 (8.371 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7174\n",
            "INFO:tensorflow:loss = 2.288373, step = 14800 (8.536 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8794\n",
            "INFO:tensorflow:loss = 2.2883217, step = 14900 (8.419 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7154\n",
            "INFO:tensorflow:loss = 2.2994184, step = 15000 (8.536 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.898\n",
            "INFO:tensorflow:loss = 2.2970726, step = 15100 (8.403 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6568\n",
            "INFO:tensorflow:loss = 2.3001177, step = 15200 (8.579 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8643\n",
            "INFO:tensorflow:loss = 2.3021967, step = 15300 (8.431 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.679\n",
            "INFO:tensorflow:loss = 2.2961948, step = 15400 (8.559 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8799\n",
            "INFO:tensorflow:loss = 2.304731, step = 15500 (8.416 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6425\n",
            "INFO:tensorflow:loss = 2.3025837, step = 15600 (8.589 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.85\n",
            "INFO:tensorflow:loss = 2.2985098, step = 15700 (8.439 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.683\n",
            "INFO:tensorflow:loss = 2.2999253, step = 15800 (8.562 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8782\n",
            "INFO:tensorflow:loss = 2.2957036, step = 15900 (8.419 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.663\n",
            "INFO:tensorflow:loss = 2.3041275, step = 16000 (8.573 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.857\n",
            "INFO:tensorflow:loss = 2.3023803, step = 16100 (8.434 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7477\n",
            "INFO:tensorflow:loss = 2.3105216, step = 16200 (8.512 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8573\n",
            "INFO:tensorflow:loss = 2.2920377, step = 16300 (8.433 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6848\n",
            "INFO:tensorflow:loss = 2.3002808, step = 16400 (8.559 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8734\n",
            "INFO:tensorflow:loss = 2.2901704, step = 16500 (8.421 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7012\n",
            "INFO:tensorflow:loss = 2.2950857, step = 16600 (8.549 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.833\n",
            "INFO:tensorflow:loss = 2.3008277, step = 16700 (8.450 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6801\n",
            "INFO:tensorflow:loss = 2.2975473, step = 16800 (8.561 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9097\n",
            "INFO:tensorflow:loss = 2.302228, step = 16900 (8.396 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6591\n",
            "INFO:tensorflow:loss = 2.2968616, step = 17000 (8.577 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8447\n",
            "INFO:tensorflow:loss = 2.3029034, step = 17100 (8.443 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6512\n",
            "INFO:tensorflow:loss = 2.2898426, step = 17200 (8.581 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9018\n",
            "INFO:tensorflow:loss = 2.293703, step = 17300 (8.403 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6885\n",
            "INFO:tensorflow:loss = 2.3034594, step = 17400 (8.553 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8577\n",
            "INFO:tensorflow:loss = 2.2886217, step = 17500 (8.433 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7106\n",
            "INFO:tensorflow:loss = 2.2882001, step = 17600 (8.542 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8859\n",
            "INFO:tensorflow:loss = 2.294006, step = 17700 (8.414 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6767\n",
            "INFO:tensorflow:loss = 2.2890532, step = 17800 (8.561 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8928\n",
            "INFO:tensorflow:loss = 2.2903335, step = 17900 (8.412 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7096\n",
            "INFO:tensorflow:loss = 2.3006577, step = 18000 (8.540 sec)\n",
            "INFO:tensorflow:Saving checkpoints for 18078 into /tmp/mnist_vgg13_model/model.ckpt.\n",
            "INFO:tensorflow:global_step/sec: 11.4695\n",
            "INFO:tensorflow:loss = 2.291237, step = 18100 (8.715 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8651\n",
            "INFO:tensorflow:loss = 2.3021758, step = 18200 (8.430 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6948\n",
            "INFO:tensorflow:loss = 2.2867804, step = 18300 (8.551 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8356\n",
            "INFO:tensorflow:loss = 2.2904084, step = 18400 (8.447 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6642\n",
            "INFO:tensorflow:loss = 2.3018138, step = 18500 (8.577 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9255\n",
            "INFO:tensorflow:loss = 2.296788, step = 18600 (8.384 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.693\n",
            "INFO:tensorflow:loss = 2.291788, step = 18700 (8.552 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8809\n",
            "INFO:tensorflow:loss = 2.2981026, step = 18800 (8.415 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.761\n",
            "INFO:tensorflow:loss = 2.2879336, step = 18900 (8.504 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.96\n",
            "INFO:tensorflow:loss = 2.2955122, step = 19000 (8.362 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7146\n",
            "INFO:tensorflow:loss = 2.2911005, step = 19100 (8.533 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9364\n",
            "INFO:tensorflow:loss = 2.2965322, step = 19200 (8.381 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7419\n",
            "INFO:tensorflow:loss = 2.2915227, step = 19300 (8.516 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9017\n",
            "INFO:tensorflow:loss = 2.2963264, step = 19400 (8.402 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7407\n",
            "INFO:tensorflow:loss = 2.288618, step = 19500 (8.518 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9401\n",
            "INFO:tensorflow:loss = 2.2871091, step = 19600 (8.375 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8017\n",
            "INFO:tensorflow:loss = 2.2991056, step = 19700 (8.473 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9558\n",
            "INFO:tensorflow:loss = 2.2945054, step = 19800 (8.365 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.819\n",
            "INFO:tensorflow:loss = 2.2996793, step = 19900 (8.460 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9476\n",
            "INFO:tensorflow:loss = 2.2923453, step = 20000 (8.370 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7794\n",
            "INFO:tensorflow:loss = 2.29544, step = 20100 (8.487 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.952\n",
            "INFO:tensorflow:loss = 2.3008277, step = 20200 (8.369 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8224\n",
            "INFO:tensorflow:loss = 2.2952764, step = 20300 (8.457 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9414\n",
            "INFO:tensorflow:loss = 2.2922137, step = 20400 (8.376 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8294\n",
            "INFO:tensorflow:loss = 2.2788804, step = 20500 (8.453 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9811\n",
            "INFO:tensorflow:loss = 2.2870035, step = 20600 (8.346 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8272\n",
            "INFO:tensorflow:loss = 2.289479, step = 20700 (8.455 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.958\n",
            "INFO:tensorflow:loss = 2.2993844, step = 20800 (8.362 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7928\n",
            "INFO:tensorflow:loss = 2.2850688, step = 20900 (8.480 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9297\n",
            "INFO:tensorflow:loss = 2.2845216, step = 21000 (8.384 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.782\n",
            "INFO:tensorflow:loss = 2.28307, step = 21100 (8.485 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9361\n",
            "INFO:tensorflow:loss = 2.2752595, step = 21200 (8.376 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8142\n",
            "INFO:tensorflow:loss = 2.2969205, step = 21300 (8.464 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9632\n",
            "INFO:tensorflow:loss = 2.2828116, step = 21400 (8.362 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7797\n",
            "INFO:tensorflow:loss = 2.2876484, step = 21500 (8.490 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9242\n",
            "INFO:tensorflow:loss = 2.283126, step = 21600 (8.384 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7965\n",
            "INFO:tensorflow:loss = 2.2802343, step = 21700 (8.479 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9559\n",
            "INFO:tensorflow:loss = 2.289603, step = 21800 (8.364 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8385\n",
            "INFO:tensorflow:loss = 2.287139, step = 21900 (8.447 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9625\n",
            "INFO:tensorflow:loss = 2.2758858, step = 22000 (8.359 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8015\n",
            "INFO:tensorflow:loss = 2.2911901, step = 22100 (8.473 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9242\n",
            "INFO:tensorflow:loss = 2.2752054, step = 22200 (8.388 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7772\n",
            "INFO:tensorflow:loss = 2.2768898, step = 22300 (8.487 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9003\n",
            "INFO:tensorflow:loss = 2.292966, step = 22400 (8.407 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7931\n",
            "INFO:tensorflow:loss = 2.2828078, step = 22500 (8.478 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.959\n",
            "INFO:tensorflow:loss = 2.2830513, step = 22600 (8.362 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.808\n",
            "INFO:tensorflow:loss = 2.2867994, step = 22700 (8.470 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9425\n",
            "INFO:tensorflow:loss = 2.2694275, step = 22800 (8.371 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8142\n",
            "INFO:tensorflow:loss = 2.2823853, step = 22900 (8.467 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9557\n",
            "INFO:tensorflow:loss = 2.27758, step = 23000 (8.364 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8161\n",
            "INFO:tensorflow:loss = 2.2715955, step = 23100 (8.461 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9598\n",
            "INFO:tensorflow:loss = 2.2684438, step = 23200 (8.364 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8175\n",
            "INFO:tensorflow:loss = 2.2651377, step = 23300 (8.461 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9453\n",
            "INFO:tensorflow:loss = 2.2851002, step = 23400 (8.369 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.814\n",
            "INFO:tensorflow:loss = 2.285421, step = 23500 (8.466 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9524\n",
            "INFO:tensorflow:loss = 2.2669735, step = 23600 (8.367 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8268\n",
            "INFO:tensorflow:loss = 2.260436, step = 23700 (8.454 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9458\n",
            "INFO:tensorflow:loss = 2.2581723, step = 23800 (8.372 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8124\n",
            "INFO:tensorflow:loss = 2.2707589, step = 23900 (8.465 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9442\n",
            "INFO:tensorflow:loss = 2.2599869, step = 24000 (8.370 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8106\n",
            "INFO:tensorflow:loss = 2.2572706, step = 24100 (8.467 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9725\n",
            "INFO:tensorflow:loss = 2.262963, step = 24200 (8.354 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8022\n",
            "INFO:tensorflow:loss = 2.2529871, step = 24300 (8.473 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9675\n",
            "INFO:tensorflow:loss = 2.2286735, step = 24400 (8.354 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8383\n",
            "INFO:tensorflow:loss = 2.2501974, step = 24500 (8.450 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9608\n",
            "INFO:tensorflow:loss = 2.2248585, step = 24600 (8.361 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8175\n",
            "INFO:tensorflow:loss = 2.2247458, step = 24700 (8.461 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9575\n",
            "INFO:tensorflow:loss = 2.2285128, step = 24800 (8.362 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.841\n",
            "INFO:tensorflow:loss = 2.2152886, step = 24900 (8.445 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9802\n",
            "INFO:tensorflow:loss = 2.2265759, step = 25000 (8.349 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8179\n",
            "INFO:tensorflow:loss = 2.2086282, step = 25100 (8.463 sec)\n",
            "INFO:tensorflow:Saving checkpoints for 25195 into /tmp/mnist_vgg13_model/model.ckpt.\n",
            "INFO:tensorflow:global_step/sec: 11.5032\n",
            "INFO:tensorflow:loss = 2.1958728, step = 25200 (8.694 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7747\n",
            "INFO:tensorflow:loss = 2.1793785, step = 25300 (8.491 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9539\n",
            "INFO:tensorflow:loss = 2.1515877, step = 25400 (8.366 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.818\n",
            "INFO:tensorflow:loss = 2.1186955, step = 25500 (8.462 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9607\n",
            "INFO:tensorflow:loss = 2.137616, step = 25600 (8.359 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8048\n",
            "INFO:tensorflow:loss = 2.125544, step = 25700 (8.471 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9381\n",
            "INFO:tensorflow:loss = 2.0805128, step = 25800 (8.377 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8134\n",
            "INFO:tensorflow:loss = 2.010973, step = 25900 (8.464 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9611\n",
            "INFO:tensorflow:loss = 1.9254123, step = 26000 (8.363 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8015\n",
            "INFO:tensorflow:loss = 1.9930022, step = 26100 (8.473 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9655\n",
            "INFO:tensorflow:loss = 1.8636909, step = 26200 (8.358 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.821\n",
            "INFO:tensorflow:loss = 1.6630645, step = 26300 (8.457 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9692\n",
            "INFO:tensorflow:loss = 1.6670932, step = 26400 (8.357 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7872\n",
            "INFO:tensorflow:loss = 1.3752817, step = 26500 (8.483 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9643\n",
            "INFO:tensorflow:loss = 1.2321088, step = 26600 (8.356 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7998\n",
            "INFO:tensorflow:loss = 1.1958976, step = 26700 (8.475 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9388\n",
            "INFO:tensorflow:loss = 1.0553778, step = 26800 (8.380 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7579\n",
            "INFO:tensorflow:loss = 0.93163186, step = 26900 (8.503 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9249\n",
            "INFO:tensorflow:loss = 0.9980302, step = 27000 (8.386 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7783\n",
            "INFO:tensorflow:loss = 0.90312475, step = 27100 (8.490 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9218\n",
            "INFO:tensorflow:loss = 0.82997566, step = 27200 (8.389 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7954\n",
            "INFO:tensorflow:loss = 0.7064795, step = 27300 (8.478 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9533\n",
            "INFO:tensorflow:loss = 0.8908912, step = 27400 (8.363 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8066\n",
            "INFO:tensorflow:loss = 0.64582735, step = 27500 (8.474 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9466\n",
            "INFO:tensorflow:loss = 0.5336154, step = 27600 (8.368 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7823\n",
            "INFO:tensorflow:loss = 0.61612666, step = 27700 (8.485 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8884\n",
            "INFO:tensorflow:loss = 0.68554443, step = 27800 (8.414 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7203\n",
            "INFO:tensorflow:loss = 0.6109189, step = 27900 (8.532 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9286\n",
            "INFO:tensorflow:loss = 0.54129106, step = 28000 (8.381 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7889\n",
            "INFO:tensorflow:loss = 0.77150774, step = 28100 (8.484 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9417\n",
            "INFO:tensorflow:loss = 0.72110635, step = 28200 (8.373 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.79\n",
            "INFO:tensorflow:loss = 0.5152898, step = 28300 (8.482 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9621\n",
            "INFO:tensorflow:loss = 0.53479743, step = 28400 (8.361 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7976\n",
            "INFO:tensorflow:loss = 0.33223698, step = 28500 (8.476 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9375\n",
            "INFO:tensorflow:loss = 0.45246315, step = 28600 (8.375 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7709\n",
            "INFO:tensorflow:loss = 0.38770658, step = 28700 (8.497 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9239\n",
            "INFO:tensorflow:loss = 0.5067716, step = 28800 (8.385 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7531\n",
            "INFO:tensorflow:loss = 0.548948, step = 28900 (8.508 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.917\n",
            "INFO:tensorflow:loss = 0.5286694, step = 29000 (8.395 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7299\n",
            "INFO:tensorflow:loss = 0.45010018, step = 29100 (8.525 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.907\n",
            "INFO:tensorflow:loss = 0.33983025, step = 29200 (8.397 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7457\n",
            "INFO:tensorflow:loss = 0.23276575, step = 29300 (8.512 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9109\n",
            "INFO:tensorflow:loss = 0.2849316, step = 29400 (8.398 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7606\n",
            "INFO:tensorflow:loss = 0.23705497, step = 29500 (8.501 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9367\n",
            "INFO:tensorflow:loss = 0.2589172, step = 29600 (8.380 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7796\n",
            "INFO:tensorflow:loss = 0.29166913, step = 29700 (8.490 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9495\n",
            "INFO:tensorflow:loss = 0.38716388, step = 29800 (8.368 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7919\n",
            "INFO:tensorflow:loss = 0.30210447, step = 29900 (8.480 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9402\n",
            "INFO:tensorflow:loss = 0.4019292, step = 30000 (8.375 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8053\n",
            "INFO:tensorflow:loss = 0.40450466, step = 30100 (8.471 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9398\n",
            "INFO:tensorflow:loss = 0.31242266, step = 30200 (8.374 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7994\n",
            "INFO:tensorflow:loss = 0.33558118, step = 30300 (8.478 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9386\n",
            "INFO:tensorflow:loss = 0.21083988, step = 30400 (8.376 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7946\n",
            "INFO:tensorflow:loss = 0.33213842, step = 30500 (8.477 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9382\n",
            "INFO:tensorflow:loss = 0.30189347, step = 30600 (8.375 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7778\n",
            "INFO:tensorflow:loss = 0.38981137, step = 30700 (8.492 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9309\n",
            "INFO:tensorflow:loss = 0.23686258, step = 30800 (8.382 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.804\n",
            "INFO:tensorflow:loss = 0.27505502, step = 30900 (8.472 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9304\n",
            "INFO:tensorflow:loss = 0.39144439, step = 31000 (8.380 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.776\n",
            "INFO:tensorflow:loss = 0.2482379, step = 31100 (8.493 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9448\n",
            "INFO:tensorflow:loss = 0.28402743, step = 31200 (8.374 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7684\n",
            "INFO:tensorflow:loss = 0.1974656, step = 31300 (8.494 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9231\n",
            "INFO:tensorflow:loss = 0.23586802, step = 31400 (8.389 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7628\n",
            "INFO:tensorflow:loss = 0.16824329, step = 31500 (8.502 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9108\n",
            "INFO:tensorflow:loss = 0.24682581, step = 31600 (8.395 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7598\n",
            "INFO:tensorflow:loss = 0.23462734, step = 31700 (8.502 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9471\n",
            "INFO:tensorflow:loss = 0.18767321, step = 31800 (8.370 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7834\n",
            "INFO:tensorflow:loss = 0.19166547, step = 31900 (8.491 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9079\n",
            "INFO:tensorflow:loss = 0.09678094, step = 32000 (8.396 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7419\n",
            "INFO:tensorflow:loss = 0.2532827, step = 32100 (8.515 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9147\n",
            "INFO:tensorflow:loss = 0.16872558, step = 32200 (8.392 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7234\n",
            "INFO:tensorflow:loss = 0.32973114, step = 32300 (8.534 sec)\n",
            "INFO:tensorflow:Saving checkpoints for 32306 into /tmp/mnist_vgg13_model/model.ckpt.\n",
            "WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:960: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.\n",
            "Instructions for updating:\n",
            "Use standard file APIs to delete files with this prefix.\n",
            "INFO:tensorflow:global_step/sec: 11.4004\n",
            "INFO:tensorflow:loss = 0.0944288, step = 32400 (8.768 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9022\n",
            "INFO:tensorflow:loss = 0.21146733, step = 32500 (8.402 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7471\n",
            "INFO:tensorflow:loss = 0.15692434, step = 32600 (8.513 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8803\n",
            "INFO:tensorflow:loss = 0.18851064, step = 32700 (8.419 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7647\n",
            "INFO:tensorflow:loss = 0.23542668, step = 32800 (8.500 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9041\n",
            "INFO:tensorflow:loss = 0.19095631, step = 32900 (8.400 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7761\n",
            "INFO:tensorflow:loss = 0.22745827, step = 33000 (8.493 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9443\n",
            "INFO:tensorflow:loss = 0.1553292, step = 33100 (8.372 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7678\n",
            "INFO:tensorflow:loss = 0.102004156, step = 33200 (8.494 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9414\n",
            "INFO:tensorflow:loss = 0.17764439, step = 33300 (8.378 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8051\n",
            "INFO:tensorflow:loss = 0.1988576, step = 33400 (8.469 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9114\n",
            "INFO:tensorflow:loss = 0.18595082, step = 33500 (8.394 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7697\n",
            "INFO:tensorflow:loss = 0.24661791, step = 33600 (8.501 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9311\n",
            "INFO:tensorflow:loss = 0.09397456, step = 33700 (8.377 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7694\n",
            "INFO:tensorflow:loss = 0.19523868, step = 33800 (8.501 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9298\n",
            "INFO:tensorflow:loss = 0.19754326, step = 33900 (8.380 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8024\n",
            "INFO:tensorflow:loss = 0.18533057, step = 34000 (8.475 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9365\n",
            "INFO:tensorflow:loss = 0.07082811, step = 34100 (8.374 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7886\n",
            "INFO:tensorflow:loss = 0.113102876, step = 34200 (8.485 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9294\n",
            "INFO:tensorflow:loss = 0.19103403, step = 34300 (8.383 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7766\n",
            "INFO:tensorflow:loss = 0.09480227, step = 34400 (8.489 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9434\n",
            "INFO:tensorflow:loss = 0.21756771, step = 34500 (8.376 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8149\n",
            "INFO:tensorflow:loss = 0.19431068, step = 34600 (8.461 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9237\n",
            "INFO:tensorflow:loss = 0.2301381, step = 34700 (8.386 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8166\n",
            "INFO:tensorflow:loss = 0.13754246, step = 34800 (8.465 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9196\n",
            "INFO:tensorflow:loss = 0.10667003, step = 34900 (8.389 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8149\n",
            "INFO:tensorflow:loss = 0.1774022, step = 35000 (8.465 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9329\n",
            "INFO:tensorflow:loss = 0.124092415, step = 35100 (8.378 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7976\n",
            "INFO:tensorflow:loss = 0.16609067, step = 35200 (8.479 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9242\n",
            "INFO:tensorflow:loss = 0.097132616, step = 35300 (8.386 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7862\n",
            "INFO:tensorflow:loss = 0.2124849, step = 35400 (8.485 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9299\n",
            "INFO:tensorflow:loss = 0.1315649, step = 35500 (8.382 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7987\n",
            "INFO:tensorflow:loss = 0.06484604, step = 35600 (8.475 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9258\n",
            "INFO:tensorflow:loss = 0.25490844, step = 35700 (8.385 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8066\n",
            "INFO:tensorflow:loss = 0.16521843, step = 35800 (8.471 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9419\n",
            "INFO:tensorflow:loss = 0.09551238, step = 35900 (8.373 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7869\n",
            "INFO:tensorflow:loss = 0.14733247, step = 36000 (8.484 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9219\n",
            "INFO:tensorflow:loss = 0.22290191, step = 36100 (8.389 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7771\n",
            "INFO:tensorflow:loss = 0.14099234, step = 36200 (8.491 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9188\n",
            "INFO:tensorflow:loss = 0.07563249, step = 36300 (8.388 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7909\n",
            "INFO:tensorflow:loss = 0.18288314, step = 36400 (8.479 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.955\n",
            "INFO:tensorflow:loss = 0.20805107, step = 36500 (8.368 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8112\n",
            "INFO:tensorflow:loss = 0.1597955, step = 36600 (8.465 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.923\n",
            "INFO:tensorflow:loss = 0.060717102, step = 36700 (8.387 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.803\n",
            "INFO:tensorflow:loss = 0.07374321, step = 36800 (8.472 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9294\n",
            "INFO:tensorflow:loss = 0.047066964, step = 36900 (8.384 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7581\n",
            "INFO:tensorflow:loss = 0.08650513, step = 37000 (8.504 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9222\n",
            "INFO:tensorflow:loss = 0.06829221, step = 37100 (8.386 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7953\n",
            "INFO:tensorflow:loss = 0.15369107, step = 37200 (8.479 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9102\n",
            "INFO:tensorflow:loss = 0.05112505, step = 37300 (8.397 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7849\n",
            "INFO:tensorflow:loss = 0.07361851, step = 37400 (8.484 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9288\n",
            "INFO:tensorflow:loss = 0.12271179, step = 37500 (8.381 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7808\n",
            "INFO:tensorflow:loss = 0.16007075, step = 37600 (8.488 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9157\n",
            "INFO:tensorflow:loss = 0.10075763, step = 37700 (8.394 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7912\n",
            "INFO:tensorflow:loss = 0.19571503, step = 37800 (8.480 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9334\n",
            "INFO:tensorflow:loss = 0.074772246, step = 37900 (8.380 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7656\n",
            "INFO:tensorflow:loss = 0.13499834, step = 38000 (8.502 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9057\n",
            "INFO:tensorflow:loss = 0.068489544, step = 38100 (8.399 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7968\n",
            "INFO:tensorflow:loss = 0.07873143, step = 38200 (8.474 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9111\n",
            "INFO:tensorflow:loss = 0.1395253, step = 38300 (8.399 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7569\n",
            "INFO:tensorflow:loss = 0.14833497, step = 38400 (8.503 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.929\n",
            "INFO:tensorflow:loss = 0.1242676, step = 38500 (8.384 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8246\n",
            "INFO:tensorflow:loss = 0.10539198, step = 38600 (8.458 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9427\n",
            "INFO:tensorflow:loss = 0.04935166, step = 38700 (8.373 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7478\n",
            "INFO:tensorflow:loss = 0.20427683, step = 38800 (8.514 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9125\n",
            "INFO:tensorflow:loss = 0.1537883, step = 38900 (8.393 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7719\n",
            "INFO:tensorflow:loss = 0.05983864, step = 39000 (8.496 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9168\n",
            "INFO:tensorflow:loss = 0.105283946, step = 39100 (8.391 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.798\n",
            "INFO:tensorflow:loss = 0.07195506, step = 39200 (8.476 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9177\n",
            "INFO:tensorflow:loss = 0.0993258, step = 39300 (8.388 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7836\n",
            "INFO:tensorflow:loss = 0.093127854, step = 39400 (8.490 sec)\n",
            "INFO:tensorflow:Saving checkpoints for 39416 into /tmp/mnist_vgg13_model/model.ckpt.\n",
            "INFO:tensorflow:global_step/sec: 11.5145\n",
            "INFO:tensorflow:loss = 0.094045, step = 39500 (8.684 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7423\n",
            "INFO:tensorflow:loss = 0.08435568, step = 39600 (8.517 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9098\n",
            "INFO:tensorflow:loss = 0.07479754, step = 39700 (8.397 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7689\n",
            "INFO:tensorflow:loss = 0.044642705, step = 39800 (8.496 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8981\n",
            "INFO:tensorflow:loss = 0.11084891, step = 39900 (8.405 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7882\n",
            "INFO:tensorflow:loss = 0.097423784, step = 40000 (8.483 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9334\n",
            "INFO:tensorflow:loss = 0.04197345, step = 40100 (8.381 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7133\n",
            "INFO:tensorflow:loss = 0.09733913, step = 40200 (8.534 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9114\n",
            "INFO:tensorflow:loss = 0.10947388, step = 40300 (8.395 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7902\n",
            "INFO:tensorflow:loss = 0.07981684, step = 40400 (8.484 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9339\n",
            "INFO:tensorflow:loss = 0.0893639, step = 40500 (8.380 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7771\n",
            "INFO:tensorflow:loss = 0.08282029, step = 40600 (8.491 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.914\n",
            "INFO:tensorflow:loss = 0.1076888, step = 40700 (8.390 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7819\n",
            "INFO:tensorflow:loss = 0.06917061, step = 40800 (8.488 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9298\n",
            "INFO:tensorflow:loss = 0.057957076, step = 40900 (8.385 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7798\n",
            "INFO:tensorflow:loss = 0.054264065, step = 41000 (8.487 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9295\n",
            "INFO:tensorflow:loss = 0.18256849, step = 41100 (8.386 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8\n",
            "INFO:tensorflow:loss = 0.05571352, step = 41200 (8.472 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9846\n",
            "INFO:tensorflow:loss = 0.07029057, step = 41300 (8.344 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8278\n",
            "INFO:tensorflow:loss = 0.10447287, step = 41400 (8.455 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9214\n",
            "INFO:tensorflow:loss = 0.048627816, step = 41500 (8.386 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7715\n",
            "INFO:tensorflow:loss = 0.20843603, step = 41600 (8.498 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9109\n",
            "INFO:tensorflow:loss = 0.12836906, step = 41700 (8.399 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7567\n",
            "INFO:tensorflow:loss = 0.07060857, step = 41800 (8.504 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9368\n",
            "INFO:tensorflow:loss = 0.12904663, step = 41900 (8.374 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7993\n",
            "INFO:tensorflow:loss = 0.072683394, step = 42000 (8.477 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9354\n",
            "INFO:tensorflow:loss = 0.07077434, step = 42100 (8.378 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7529\n",
            "INFO:tensorflow:loss = 0.106637865, step = 42200 (8.508 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9491\n",
            "INFO:tensorflow:loss = 0.087547585, step = 42300 (8.368 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8135\n",
            "INFO:tensorflow:loss = 0.07004271, step = 42400 (8.467 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9249\n",
            "INFO:tensorflow:loss = 0.116223685, step = 42500 (8.383 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8054\n",
            "INFO:tensorflow:loss = 0.18411264, step = 42600 (8.473 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9066\n",
            "INFO:tensorflow:loss = 0.1417898, step = 42700 (8.398 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8244\n",
            "INFO:tensorflow:loss = 0.057653543, step = 42800 (8.458 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9269\n",
            "INFO:tensorflow:loss = 0.061787654, step = 42900 (8.382 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8265\n",
            "INFO:tensorflow:loss = 0.112374805, step = 43000 (8.456 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9468\n",
            "INFO:tensorflow:loss = 0.0733743, step = 43100 (8.373 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7935\n",
            "INFO:tensorflow:loss = 0.066446565, step = 43200 (8.479 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9332\n",
            "INFO:tensorflow:loss = 0.10527719, step = 43300 (8.380 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.807\n",
            "INFO:tensorflow:loss = 0.038081594, step = 43400 (8.471 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9692\n",
            "INFO:tensorflow:loss = 0.06396591, step = 43500 (8.353 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8079\n",
            "INFO:tensorflow:loss = 0.024763228, step = 43600 (8.468 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9151\n",
            "INFO:tensorflow:loss = 0.049540926, step = 43700 (8.394 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7966\n",
            "INFO:tensorflow:loss = 0.055082336, step = 43800 (8.478 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9505\n",
            "INFO:tensorflow:loss = 0.15367372, step = 43900 (8.367 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7645\n",
            "INFO:tensorflow:loss = 0.103573285, step = 44000 (8.501 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9073\n",
            "INFO:tensorflow:loss = 0.1381395, step = 44100 (8.397 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7691\n",
            "INFO:tensorflow:loss = 0.08018106, step = 44200 (8.498 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9145\n",
            "INFO:tensorflow:loss = 0.05367272, step = 44300 (8.392 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7467\n",
            "INFO:tensorflow:loss = 0.10364188, step = 44400 (8.511 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9053\n",
            "INFO:tensorflow:loss = 0.09015094, step = 44500 (8.403 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7572\n",
            "INFO:tensorflow:loss = 0.025217628, step = 44600 (8.506 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9143\n",
            "INFO:tensorflow:loss = 0.020100176, step = 44700 (8.392 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.736\n",
            "INFO:tensorflow:loss = 0.03802904, step = 44800 (8.519 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9166\n",
            "INFO:tensorflow:loss = 0.06808453, step = 44900 (8.395 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7375\n",
            "INFO:tensorflow:loss = 0.10010614, step = 45000 (8.519 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9022\n",
            "INFO:tensorflow:loss = 0.08496203, step = 45100 (8.402 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7526\n",
            "INFO:tensorflow:loss = 0.08940413, step = 45200 (8.507 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9284\n",
            "INFO:tensorflow:loss = 0.025395107, step = 45300 (8.385 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7833\n",
            "INFO:tensorflow:loss = 0.060802184, step = 45400 (8.486 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.902\n",
            "INFO:tensorflow:loss = 0.09549969, step = 45500 (8.404 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7407\n",
            "INFO:tensorflow:loss = 0.08005771, step = 45600 (8.517 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9147\n",
            "INFO:tensorflow:loss = 0.034812964, step = 45700 (8.392 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.733\n",
            "INFO:tensorflow:loss = 0.20087749, step = 45800 (8.522 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9212\n",
            "INFO:tensorflow:loss = 0.08894938, step = 45900 (8.389 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7172\n",
            "INFO:tensorflow:loss = 0.062309217, step = 46000 (8.540 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8709\n",
            "INFO:tensorflow:loss = 0.07831378, step = 46100 (8.419 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7037\n",
            "INFO:tensorflow:loss = 0.06595624, step = 46200 (8.542 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8891\n",
            "INFO:tensorflow:loss = 0.08456888, step = 46300 (8.412 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7168\n",
            "INFO:tensorflow:loss = 0.08643276, step = 46400 (8.535 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8977\n",
            "INFO:tensorflow:loss = 0.1351603, step = 46500 (8.405 sec)\n",
            "INFO:tensorflow:Saving checkpoints for 46521 into /tmp/mnist_vgg13_model/model.ckpt.\n",
            "INFO:tensorflow:global_step/sec: 11.4498\n",
            "INFO:tensorflow:loss = 0.065038584, step = 46600 (8.732 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7556\n",
            "INFO:tensorflow:loss = 0.054711014, step = 46700 (8.506 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8994\n",
            "INFO:tensorflow:loss = 0.07157096, step = 46800 (8.412 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7366\n",
            "INFO:tensorflow:loss = 0.034212153, step = 46900 (8.516 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8859\n",
            "INFO:tensorflow:loss = 0.18447268, step = 47000 (8.412 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.716\n",
            "INFO:tensorflow:loss = 0.12006947, step = 47100 (8.532 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9124\n",
            "INFO:tensorflow:loss = 0.023289867, step = 47200 (8.397 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7332\n",
            "INFO:tensorflow:loss = 0.017164914, step = 47300 (8.524 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.909\n",
            "INFO:tensorflow:loss = 0.10428698, step = 47400 (8.396 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7658\n",
            "INFO:tensorflow:loss = 0.04117893, step = 47500 (8.497 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9285\n",
            "INFO:tensorflow:loss = 0.06383997, step = 47600 (8.385 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7338\n",
            "INFO:tensorflow:loss = 0.05284836, step = 47700 (8.523 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9192\n",
            "INFO:tensorflow:loss = 0.06404733, step = 47800 (8.389 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7256\n",
            "INFO:tensorflow:loss = 0.20009011, step = 47900 (8.531 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9105\n",
            "INFO:tensorflow:loss = 0.10110886, step = 48000 (8.392 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7793\n",
            "INFO:tensorflow:loss = 0.047065396, step = 48100 (8.489 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8932\n",
            "INFO:tensorflow:loss = 0.113112934, step = 48200 (8.408 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7366\n",
            "INFO:tensorflow:loss = 0.026080325, step = 48300 (8.522 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9114\n",
            "INFO:tensorflow:loss = 0.04599634, step = 48400 (8.397 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7415\n",
            "INFO:tensorflow:loss = 0.02997165, step = 48500 (8.520 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8908\n",
            "INFO:tensorflow:loss = 0.0739108, step = 48600 (8.405 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7587\n",
            "INFO:tensorflow:loss = 0.014944465, step = 48700 (8.505 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8969\n",
            "INFO:tensorflow:loss = 0.070529334, step = 48800 (8.404 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7508\n",
            "INFO:tensorflow:loss = 0.0062086373, step = 48900 (8.511 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8766\n",
            "INFO:tensorflow:loss = 0.086544506, step = 49000 (8.421 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7386\n",
            "INFO:tensorflow:loss = 0.045103054, step = 49100 (8.517 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9035\n",
            "INFO:tensorflow:loss = 0.079077, step = 49200 (8.403 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7374\n",
            "INFO:tensorflow:loss = 0.07662975, step = 49300 (8.518 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8777\n",
            "INFO:tensorflow:loss = 0.11669026, step = 49400 (8.423 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7503\n",
            "INFO:tensorflow:loss = 0.026030982, step = 49500 (8.506 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9072\n",
            "INFO:tensorflow:loss = 0.13549912, step = 49600 (8.403 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6834\n",
            "INFO:tensorflow:loss = 0.08092745, step = 49700 (8.557 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8654\n",
            "INFO:tensorflow:loss = 0.0846674, step = 49800 (8.427 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7208\n",
            "INFO:tensorflow:loss = 0.018963598, step = 49900 (8.532 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8971\n",
            "INFO:tensorflow:loss = 0.014846192, step = 50000 (8.405 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7504\n",
            "INFO:tensorflow:loss = 0.026766472, step = 50100 (8.511 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9004\n",
            "INFO:tensorflow:loss = 0.06324769, step = 50200 (8.404 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7443\n",
            "INFO:tensorflow:loss = 0.026713476, step = 50300 (8.514 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8982\n",
            "INFO:tensorflow:loss = 0.04802184, step = 50400 (8.403 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7629\n",
            "INFO:tensorflow:loss = 0.02862721, step = 50500 (8.502 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9045\n",
            "INFO:tensorflow:loss = 0.049083937, step = 50600 (8.400 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7602\n",
            "INFO:tensorflow:loss = 0.0387051, step = 50700 (8.502 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8893\n",
            "INFO:tensorflow:loss = 0.10839441, step = 50800 (8.412 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7431\n",
            "INFO:tensorflow:loss = 0.07679512, step = 50900 (8.519 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9035\n",
            "INFO:tensorflow:loss = 0.030270042, step = 51000 (8.400 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7247\n",
            "INFO:tensorflow:loss = 0.0735755, step = 51100 (8.526 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8936\n",
            "INFO:tensorflow:loss = 0.02526691, step = 51200 (8.409 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7755\n",
            "INFO:tensorflow:loss = 0.11325148, step = 51300 (8.493 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9057\n",
            "INFO:tensorflow:loss = 0.034713276, step = 51400 (8.399 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7349\n",
            "INFO:tensorflow:loss = 0.059774652, step = 51500 (8.520 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.888\n",
            "INFO:tensorflow:loss = 0.05458605, step = 51600 (8.414 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7449\n",
            "INFO:tensorflow:loss = 0.052118696, step = 51700 (8.513 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9027\n",
            "INFO:tensorflow:loss = 0.009641037, step = 51800 (8.403 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.749\n",
            "INFO:tensorflow:loss = 0.014626577, step = 51900 (8.512 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9056\n",
            "INFO:tensorflow:loss = 0.021867175, step = 52000 (8.399 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.727\n",
            "INFO:tensorflow:loss = 0.08035818, step = 52100 (8.525 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8822\n",
            "INFO:tensorflow:loss = 0.082691215, step = 52200 (8.416 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7133\n",
            "INFO:tensorflow:loss = 0.03568573, step = 52300 (8.537 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9002\n",
            "INFO:tensorflow:loss = 0.09485608, step = 52400 (8.407 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7191\n",
            "INFO:tensorflow:loss = 0.08599742, step = 52500 (8.532 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8825\n",
            "INFO:tensorflow:loss = 0.08530001, step = 52600 (8.413 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7075\n",
            "INFO:tensorflow:loss = 0.052514628, step = 52700 (8.544 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9054\n",
            "INFO:tensorflow:loss = 0.054553777, step = 52800 (8.397 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7258\n",
            "INFO:tensorflow:loss = 0.05379631, step = 52900 (8.531 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8633\n",
            "INFO:tensorflow:loss = 0.020236619, step = 53000 (8.431 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7265\n",
            "INFO:tensorflow:loss = 0.104754, step = 53100 (8.526 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9189\n",
            "INFO:tensorflow:loss = 0.18459532, step = 53200 (8.389 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7189\n",
            "INFO:tensorflow:loss = 0.045755643, step = 53300 (8.536 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9047\n",
            "INFO:tensorflow:loss = 0.022342816, step = 53400 (8.400 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7556\n",
            "INFO:tensorflow:loss = 0.021217968, step = 53500 (8.505 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9076\n",
            "INFO:tensorflow:loss = 0.07004312, step = 53600 (8.398 sec)\n",
            "INFO:tensorflow:Saving checkpoints for 53609 into /tmp/mnist_vgg13_model/model.ckpt.\n",
            "INFO:tensorflow:global_step/sec: 11.3522\n",
            "INFO:tensorflow:loss = 0.106162794, step = 53700 (8.806 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.934\n",
            "INFO:tensorflow:loss = 0.03388069, step = 53800 (8.382 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7302\n",
            "INFO:tensorflow:loss = 0.02091603, step = 53900 (8.525 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8955\n",
            "INFO:tensorflow:loss = 0.07569347, step = 54000 (8.406 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7472\n",
            "INFO:tensorflow:loss = 0.076098956, step = 54100 (8.513 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8895\n",
            "INFO:tensorflow:loss = 0.012279513, step = 54200 (8.410 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7194\n",
            "INFO:tensorflow:loss = 0.081859566, step = 54300 (8.532 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8822\n",
            "INFO:tensorflow:loss = 0.14617889, step = 54400 (8.415 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7266\n",
            "INFO:tensorflow:loss = 0.052890524, step = 54500 (8.532 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9037\n",
            "INFO:tensorflow:loss = 0.02530305, step = 54600 (8.398 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.736\n",
            "INFO:tensorflow:loss = 0.1519185, step = 54700 (8.522 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8633\n",
            "INFO:tensorflow:loss = 0.07612839, step = 54800 (8.429 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6822\n",
            "INFO:tensorflow:loss = 0.025813526, step = 54900 (8.560 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8682\n",
            "INFO:tensorflow:loss = 0.009528444, step = 55000 (8.427 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7187\n",
            "INFO:tensorflow:loss = 0.016305882, step = 55100 (8.532 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.883\n",
            "INFO:tensorflow:loss = 0.10522897, step = 55200 (8.414 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7352\n",
            "INFO:tensorflow:loss = 0.06697366, step = 55300 (8.526 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8963\n",
            "INFO:tensorflow:loss = 0.035067283, step = 55400 (8.402 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7755\n",
            "INFO:tensorflow:loss = 0.023314875, step = 55500 (8.493 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9064\n",
            "INFO:tensorflow:loss = 0.03887318, step = 55600 (8.398 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7606\n",
            "INFO:tensorflow:loss = 0.055862438, step = 55700 (8.503 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9196\n",
            "INFO:tensorflow:loss = 0.060490955, step = 55800 (8.392 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7731\n",
            "INFO:tensorflow:loss = 0.02608961, step = 55900 (8.491 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9311\n",
            "INFO:tensorflow:loss = 0.04511908, step = 56000 (8.383 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7634\n",
            "INFO:tensorflow:loss = 0.018323874, step = 56100 (8.501 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9205\n",
            "INFO:tensorflow:loss = 0.016791007, step = 56200 (8.390 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7343\n",
            "INFO:tensorflow:loss = 0.015278198, step = 56300 (8.522 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9032\n",
            "INFO:tensorflow:loss = 0.023532074, step = 56400 (8.400 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7003\n",
            "INFO:tensorflow:loss = 0.11968389, step = 56500 (8.546 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8819\n",
            "INFO:tensorflow:loss = 0.08555838, step = 56600 (8.414 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7355\n",
            "INFO:tensorflow:loss = 0.03410412, step = 56700 (8.523 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8979\n",
            "INFO:tensorflow:loss = 0.04684848, step = 56800 (8.403 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7128\n",
            "INFO:tensorflow:loss = 0.01554487, step = 56900 (8.537 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.913\n",
            "INFO:tensorflow:loss = 0.049555544, step = 57000 (8.397 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7121\n",
            "INFO:tensorflow:loss = 0.01913698, step = 57100 (8.538 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9129\n",
            "INFO:tensorflow:loss = 0.057756286, step = 57200 (8.394 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7656\n",
            "INFO:tensorflow:loss = 0.09027696, step = 57300 (8.499 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9166\n",
            "INFO:tensorflow:loss = 0.023542898, step = 57400 (8.390 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7171\n",
            "INFO:tensorflow:loss = 0.035922684, step = 57500 (8.536 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9358\n",
            "INFO:tensorflow:loss = 0.07225069, step = 57600 (8.379 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7288\n",
            "INFO:tensorflow:loss = 0.009119911, step = 57700 (8.523 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8776\n",
            "INFO:tensorflow:loss = 0.07152015, step = 57800 (8.422 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6922\n",
            "INFO:tensorflow:loss = 0.041846257, step = 57900 (8.549 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9255\n",
            "INFO:tensorflow:loss = 0.009441017, step = 58000 (8.385 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7566\n",
            "INFO:tensorflow:loss = 0.12118898, step = 58100 (8.506 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9263\n",
            "INFO:tensorflow:loss = 0.038558975, step = 58200 (8.387 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7368\n",
            "INFO:tensorflow:loss = 0.063963935, step = 58300 (8.518 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9432\n",
            "INFO:tensorflow:loss = 0.058332976, step = 58400 (8.375 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7141\n",
            "INFO:tensorflow:loss = 0.041413527, step = 58500 (8.537 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8935\n",
            "INFO:tensorflow:loss = 0.058180742, step = 58600 (8.406 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6935\n",
            "INFO:tensorflow:loss = 0.057549752, step = 58700 (8.551 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9085\n",
            "INFO:tensorflow:loss = 0.020583492, step = 58800 (8.397 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.698\n",
            "INFO:tensorflow:loss = 0.04431963, step = 58900 (8.549 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8948\n",
            "INFO:tensorflow:loss = 0.019880986, step = 59000 (8.409 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.768\n",
            "INFO:tensorflow:loss = 0.017791176, step = 59100 (8.498 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.924\n",
            "INFO:tensorflow:loss = 0.024962317, step = 59200 (8.388 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.762\n",
            "INFO:tensorflow:loss = 0.041292876, step = 59300 (8.499 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9141\n",
            "INFO:tensorflow:loss = 0.037958115, step = 59400 (8.402 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7599\n",
            "INFO:tensorflow:loss = 0.022079919, step = 59500 (8.497 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.903\n",
            "INFO:tensorflow:loss = 0.016896125, step = 59600 (8.402 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7766\n",
            "INFO:tensorflow:loss = 0.041464213, step = 59700 (8.492 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9128\n",
            "INFO:tensorflow:loss = 0.058938704, step = 59800 (8.390 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7731\n",
            "INFO:tensorflow:loss = 0.0106312195, step = 59900 (8.497 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9306\n",
            "INFO:tensorflow:loss = 0.039334558, step = 60000 (8.381 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7731\n",
            "INFO:tensorflow:loss = 0.01327671, step = 60100 (8.493 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9245\n",
            "INFO:tensorflow:loss = 0.06274558, step = 60200 (8.387 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7802\n",
            "INFO:tensorflow:loss = 0.058546208, step = 60300 (8.490 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9257\n",
            "INFO:tensorflow:loss = 0.12262977, step = 60400 (8.385 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7755\n",
            "INFO:tensorflow:loss = 0.0060895495, step = 60500 (8.492 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.91\n",
            "INFO:tensorflow:loss = 0.015635308, step = 60600 (8.395 sec)\n",
            "INFO:tensorflow:Saving checkpoints for 60699 into /tmp/mnist_vgg13_model/model.ckpt.\n",
            "INFO:tensorflow:global_step/sec: 11.3921\n",
            "INFO:tensorflow:loss = 0.018765299, step = 60700 (8.776 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7769\n",
            "INFO:tensorflow:loss = 0.015916226, step = 60800 (8.493 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.932\n",
            "INFO:tensorflow:loss = 0.023275493, step = 60900 (8.379 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7902\n",
            "INFO:tensorflow:loss = 0.00930981, step = 61000 (8.483 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9284\n",
            "INFO:tensorflow:loss = 0.008088152, step = 61100 (8.384 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.781\n",
            "INFO:tensorflow:loss = 0.055403996, step = 61200 (8.486 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.938\n",
            "INFO:tensorflow:loss = 0.010177601, step = 61300 (8.377 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7956\n",
            "INFO:tensorflow:loss = 0.097187154, step = 61400 (8.480 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9398\n",
            "INFO:tensorflow:loss = 0.014858788, step = 61500 (8.375 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7875\n",
            "INFO:tensorflow:loss = 0.012550489, step = 61600 (8.483 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9174\n",
            "INFO:tensorflow:loss = 0.007973616, step = 61700 (8.392 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7831\n",
            "INFO:tensorflow:loss = 0.04119069, step = 61800 (8.487 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.903\n",
            "INFO:tensorflow:loss = 0.010587519, step = 61900 (8.398 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7477\n",
            "INFO:tensorflow:loss = 0.04795606, step = 62000 (8.513 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9254\n",
            "INFO:tensorflow:loss = 0.023211457, step = 62100 (8.385 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7647\n",
            "INFO:tensorflow:loss = 0.051675536, step = 62200 (8.502 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9285\n",
            "INFO:tensorflow:loss = 0.05675201, step = 62300 (8.383 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7756\n",
            "INFO:tensorflow:loss = 0.046855856, step = 62400 (8.492 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9164\n",
            "INFO:tensorflow:loss = 0.044177927, step = 62500 (8.392 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7749\n",
            "INFO:tensorflow:loss = 0.01357058, step = 62600 (8.492 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9194\n",
            "INFO:tensorflow:loss = 0.06851672, step = 62700 (8.390 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7607\n",
            "INFO:tensorflow:loss = 0.037933458, step = 62800 (8.501 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8913\n",
            "INFO:tensorflow:loss = 0.0067140176, step = 62900 (8.409 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7394\n",
            "INFO:tensorflow:loss = 0.018244574, step = 63000 (8.519 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.874\n",
            "INFO:tensorflow:loss = 0.014459826, step = 63100 (8.425 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7396\n",
            "INFO:tensorflow:loss = 0.011143743, step = 63200 (8.518 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8788\n",
            "INFO:tensorflow:loss = 0.00916918, step = 63300 (8.415 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.757\n",
            "INFO:tensorflow:loss = 0.06227916, step = 63400 (8.508 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8805\n",
            "INFO:tensorflow:loss = 0.11332989, step = 63500 (8.417 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.747\n",
            "INFO:tensorflow:loss = 0.08786393, step = 63600 (8.514 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8868\n",
            "INFO:tensorflow:loss = 0.06285517, step = 63700 (8.413 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7438\n",
            "INFO:tensorflow:loss = 0.058485657, step = 63800 (8.512 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9091\n",
            "INFO:tensorflow:loss = 0.04581453, step = 63900 (8.399 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7691\n",
            "INFO:tensorflow:loss = 0.010632099, step = 64000 (8.497 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9136\n",
            "INFO:tensorflow:loss = 0.007649669, step = 64100 (8.393 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7387\n",
            "INFO:tensorflow:loss = 0.028878247, step = 64200 (8.520 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9151\n",
            "INFO:tensorflow:loss = 0.02146882, step = 64300 (8.390 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7333\n",
            "INFO:tensorflow:loss = 0.016314475, step = 64400 (8.525 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.835\n",
            "INFO:tensorflow:loss = 0.028902967, step = 64500 (8.450 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6856\n",
            "INFO:tensorflow:loss = 0.004665847, step = 64600 (8.555 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8878\n",
            "INFO:tensorflow:loss = 0.014670724, step = 64700 (8.415 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.6742\n",
            "INFO:tensorflow:loss = 0.08557108, step = 64800 (8.563 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8903\n",
            "INFO:tensorflow:loss = 0.11843692, step = 64900 (8.413 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7145\n",
            "INFO:tensorflow:loss = 0.034027275, step = 65000 (8.536 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9021\n",
            "INFO:tensorflow:loss = 0.010412449, step = 65100 (8.399 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.731\n",
            "INFO:tensorflow:loss = 0.02916193, step = 65200 (8.527 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8968\n",
            "INFO:tensorflow:loss = 0.020034827, step = 65300 (8.404 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7662\n",
            "INFO:tensorflow:loss = 0.012687462, step = 65400 (8.498 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9162\n",
            "INFO:tensorflow:loss = 0.009636537, step = 65500 (8.392 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7482\n",
            "INFO:tensorflow:loss = 0.03736825, step = 65600 (8.516 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.8878\n",
            "INFO:tensorflow:loss = 0.07848531, step = 65700 (8.411 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.7439\n",
            "INFO:tensorflow:loss = 0.023099365, step = 65800 (8.516 sec)\n",
            "INFO:tensorflow:global_step/sec: 11.9268\n",
            "INFO:tensorflow:loss = 0.0077720773, step = 65900 (8.381 sec)\n",
            "INFO:tensorflow:Saving checkpoints for 66000 into /tmp/mnist_vgg13_model/model.ckpt.\n",
            "INFO:tensorflow:Loss for final step: 0.01794427.\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f65687ec7b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f65687ec7b8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f65687ec7b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f65687ec7b8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
            "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f6564917fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2020-05-09T08:47:04Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/mnist_vgg13_model/model.ckpt-66000\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2020-05-09-08:47:07\n",
            "INFO:tensorflow:Saving dict for global step 66000: accuracy = 0.982, global_step = 66000, loss = 0.05622739\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 66000: /tmp/mnist_vgg13_model/model.ckpt-66000\n",
            "{'accuracy': 0.982, 'loss': 0.05622739, 'global_step': 66000}\n"
          ],
          "name": "stdout"
        }
      ]
    }
  ]
}